# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce60068e764487127a5f7604e25821b5891acc3a89016ec670978149a69c9ea54b81cfbfb2a719696bfd8384f87982d9cf112ae11052b425b0df4fdfef35be2c

test:
  secret_key_base: be55b277f0165ead35d277c57dda86160a3b604570f61c7575e7b36848625178b20974f7bf8cd5bf77efb6599a160b783ad0d13aee643f60b3b19bf0da0867e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
